# Generated by Django 3.1.5 on 2021-01-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='upload_file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
