# Generated by Django 3.1.5 on 2021-01-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210123_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadModel',
            new_name='Upload',
        ),
    ]
