# Generated by Django 3.1.5 on 2021-01-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210123_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
